name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.4
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install specific npm version
        run: npm install -g npm@8.19.4

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: "backend"
          heroku_api_key: "HRKU-eab5f280-333c-4a4c-a891-4f0203c8d84c"
          heroku_app_name: "preemly_backend"
          heroku_email: "myrinets.bohdan@gmail.com"
          region: "eu"