name: Deploy Backend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ vars.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
          working-directory: ./backend
        env:
          MONGO_URI: ${{ vars.MONGO_URI }}
          PORT: ${{ vars.PORT }}
          MAILGUN_KEY: ${{ vars.MAILGUN_KEY }}
          API_KEY: ${{ vars.API_KEY }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          CLOUDINARY_CLOUD_NAME: ${{ vars.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ vars.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ vars.CLOUDINARY_API_SECRET }}
