name: Deploy Backend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
          working-directory: ./backend
        env:
            MONGO_URI: ${{ secrets.MONGO_URI }}
            PORT: ${{ secrets.PORT }}
            MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
            API_KEY: ${{ secrets.API_KEY }}
            AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
            CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
            VITE_APP_AUDIENCE: ${{ secrets.VITE_APP_AUDIENCE }}
            VITE_APP_DOMAIN: ${{ secrets.VITE_APP_DOMAIN }}
            VITE_APP_CLIENTID: ${{ secrets.VITE_APP_CLIENTID }}
            VITE_APP_WS_URL: ${{ secrets.VITE_APP_WS_URL }}
