name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./backend

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Проверка переменных окружения
        run: |
          echo "PORT is set to: $PORT"
        env:
          PORT: ${{ secrets.PORT }}

      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          working-directory: ./frontend
          vercel-args: '--prod'

      - name: Start backend
        run: npm run start
        working-directory: ./backend
