name: Deploy Backend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Navigate to backend directory
        run: cd ./backend

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: "HRKU-eab5f280-333c-4a4c-a891-4f0203c8d84c"
          heroku_app_name: "preemly"
          heroku_email: "myrinets.bohdan@gmail.com"